version: '3'
services:
  dev:
    container_name: file_explorer_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  prod:
    container_name: file_explorer_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'